version: '3'

services:
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'
  reisapi:
    restart: unless-stopped
    build: ./ReisAPI
    ports:
      - '8080:80'
  ticketservice:
    restart: unless-stopped
    build: ./TicketService
    depends_on:
      - ticketservice.db
  ticketservice.db:
    restart: unless-stopped
    image: mongo:5-focal
    volumes:
      - ticketservice.db:/data/db
  huurautoservice:
    restart: unless-stopped
    build: ./HuurautoService
    depends_on:
      - huurautoservice.db
  huurautoservice.db:
    restart: unless-stopped
    image: mongo:5-focal
    volumes:
      - huurautoservice.db:/data/db
  hotelservice:
    restart: unless-stopped
    build: ./HotelService
    depends_on:
      - hotelservice.db
  hotelservice.db:
    restart: unless-stopped
    image: mongo:5-focal
    volumes:
      - hotelservice.db:/data/db
  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=ticketservice.db

volumes:
  rabbitmq:
  ticketservice.db:
  huurautoservice.db:
  hotelservice.db:
